CityFoodReview/config/routes.rb
Rails.application.routes.draw do
resources :cities do
  resources :restaurants do
    resources :votes
  end		
end

   root 'home#index'

end

CityFoodReview/app/models/city.rb
class City < ActiveRecord::Base
  has_many :restaurants
  validates :name, presence: true,
                    length: { minimum: 5 }
end

CityFoodReview/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :votes
  belongs_to :city
end

CityFoodReview/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :restaurant
end

CityFoodReview/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

CityFoodReview/app/controllers/cities_controller.rb
class CitiesController < ApplicationController

	http_basic_authenticate_with name: "mazi", password: "admin", except: [:index, :show]
	http_basic_authenticate_with name: "mazi", password: "admin", only: :destroy
	
	def new
	  @city = City.new
	end

	def show #show one item
		@city = City.find(params[:id])
	end
	
	def edit
		@city = City.find(params[:id])
	end
	
	def index #show all items
		@cities = City.all.order("name")
	end
	
	def destroy
		@city = City.find(params[:id])
		@city.destroy
		redirect_to city_path
	end
	
	def create
		@city = City.new(city_params)
		if @city.save #return bool 
			redirect_to cities_path
		else #validation model fail
			render 'new' #render używane do tego samego formularza
		end
	end
	
	def update #already exiting record update
		#render plain: params[:article].inspect
		@city = City.find(params[:id])
 
		if @city.update(city_params)
			redirect_to cities_path
		else
			render 'edit'
		end
	end
	
	private def city_params #Use strong parameters mechanism
		params.require(:city).permit(:name, :photo)
	end
end

CityFoodReview/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

CityFoodReview/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	http_basic_authenticate_with name: "mazi", password: "admin", except: [:index, :show]
	http_basic_authenticate_with name: "mazi", password: "admin", only: :destroy
	
	def new
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.new
	end

	def show #show one item
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.find(params[:id])
	end
	
	def edit
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.find(params[:id])
	end
	
	def index #show all items
		@city = City.find(params[:city_id])		
		@restaurants = Restaurant.all

	end
	
	def destroy
		@restaurant = Restaurant.find(params[:id])
		@restaurant.destroy
		redirect_to restaurants_path
	end
	
	def create
		@city = City.find(params[:city_id])
		@restaurant = @city.restaurants.create(restaurant_params)
		if @restaurant.save #return bool 
			redirect_to city_restaurants_path(@city)
		else #validation model fail
			render 'new' #render używane do tego samego formularza
		end
	end
	
	def update #already exiting record update
		#render plain: params[:article].inspect
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.find(params[:id])
 
		if @restaurant.update(restaurant_params)
			redirect_to city_restaurants_path(@city)
		else
			render 'edit'
		end
	end
	
	private def restaurant_params #Use strong parameters mechanism
		params.require(:restaurant).permit(:name, :address, :remarks	, :cuisine, :photo)
	end
end

CityFoodReview/app/controllers/votes_controller.rb
class VotesController < ApplicationController

	http_basic_authenticate_with name: "mazi", password: "admin", except: [:index, :show]
	http_basic_authenticate_with name: "mazi", password: "admin", only: :destroy
	
	def new
	  @city = City.find(params[:city_id])
	  @restaurant = Restaurant.find(params[:restaurant_id])
	  @vote = Vote.new
	end

	def show #show one item
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.find(params[:restaurant_id])
		@vote = Vote.find(params[:id])
	end
	
	def edit
		@vote = Vote.find(params[:id])
	end
	
	def index #show all items
		@city = City.find(params[:city_id])
		@restaurant = Restaurant.find(params[:restaurant_id])
		@votes = Vote.all
	end
	
	def destroy
		@vote = Vote.find(params[:id])
		@vote.destroy
		redirect_to vote_path
	end
	
	def create
		@restaurant = Restaurant.find(params[:restaurant_id])
		@vote = @restaurant.votes.create(vote_params)
		if @vote.save #return bool 
			redirect_to city_restaurant_votes_path
		else #validation model fail
			render 'new' #render używane do tego samego formularza
		end
	end
	
	def update #already exiting record update
		#render plain: params[:article].inspect
		@vote = Vote.find(params[:id])
 
		if @vote.update(vote_params)
			redirect_to votes_path
		else
			render 'edit'
		end
	end
	
	private def vote_params #Use strong parameters mechanism
		params.require(:vote).permit(:voter, :vote, :comment)
	end
end

CityFoodReview/app/helpers/application_helper.rb
module ApplicationHelper
end

CityFoodReview/app/helpers/cities_helper.rb
module CitiesHelper
end

CityFoodReview/app/helpers/home_helper.rb
module HomeHelper

end

CityFoodReview/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

CityFoodReview/app/helpers/votes_helper.rb
module VotesHelper
end

CityFoodReview/app/views/cities/edit.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Restaurants rewiev - Editing city</title>
    <!-- Bootstrap Core CSS & Custom CSS-->
	<!--<%= stylesheet_link_tag   "http://localhost:3000/assets/custom.css" , media: 'all', 'data-turbolinks-track' => true%>-->


    <link href="http://localhost:3000/assets/bootstrap.min.css" rel="stylesheet">
	<link href="http://localhost:3000/assets/custom.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-togxglegle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                	<span class="glyphicon glyphicon-fire"></span> 
                	CITY FOOD REWIEV
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="http://localhost:3000">Home</a>
                    </li>
                    <li>
                        <a href="http://localhost:3000/cities">Restaurants</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ranks<span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="http://localhost:3000/cities">TOP 10</a></li>
							<li><a href="http://localhost:3000/cities">Budget rank</a></li>
						</ul>
					</li>
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
  
	<!-- Content  -->
     <section class="content content-3">
        <div class="container">
			<h2 class="section-header"><span class="glyphicon text-primary"></span><br>Edit city</h2>
			<p class="lead text-muted">
			
			<%= form_for @city do |f| %>
 
				<% if @city.errors.any? %>
				<div id="error_explanation">
				<h2>
					<%= pluralize(@city.errors.count, "error") %> No possible to save item
				</h2>
				<ul>
					<% @city.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
				</ul>
				</div>
				<% end %>
 
			<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
			</p>
			<p>
			<%= f.label :photo %><br>
			<%= f.text_field :photo %>
			</p>
			<p>
			<a href="#" class="btn btn-default btn-sx"><%= f.submit%></a>
			</p>
			<% end %>
			
			
			</p> 
			<a href="<%=cities_path%>" class="btn btn-primary btn-sx"><--cancel</a> 					
            </div>
        </div>
    </section>
    
	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-envelope"></span><br> mazi82x@gmail.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
        	<div class="container">
        		<p>Copyright xxx 2015</p>
        	</div>
        </div>
        
    </footer>
	
    <!-- jQuery -->
    <script src="http://localhost:3000/assets/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://localhost:3000/assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://localhost:3000/assets/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="http://localhost:3000/assets/custom.js"></script>

</body>

</html>

CityFoodReview/app/views/cities/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Restaurants rewiev - Cities</title>
    <!-- Bootstrap Core CSS & Custom CSS-->
	<!--<%= stylesheet_link_tag   "http://localhost:3000/assets/custom.css" , media: 'all', 'data-turbolinks-track' => true%>-->


    <link href="http://localhost:3000/assets/bootstrap.min.css" rel="stylesheet">
	<link href="http://localhost:3000/assets/custom.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-togxglegle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                	<span class="glyphicon glyphicon-fire"></span> 
                	CITY FOOD REWIEV
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="http://localhost:3000">Home</a>
                    </li>
                    <li>
                        <a href="http://localhost:3000/cities">Restaurants</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ranks<span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="http://localhost:3000/cities">TOP 10</a></li>
							<li><a href="http://localhost:3000/cities">Budget rank</a></li>
						</ul>
					</li>
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

	<!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Choose your City</h1>
            </div>
        </div>
    </header>

	<!-- Content -->
    <section class="intro">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2" align="center">
                	<span style="font-size: 60px"></span>
                    <h2 class="section-heading">The list of cities</h2>
                    <p class="text-light">
					<table cellpadding="100">
						<tr>
							<th colspan="1"></th>
						</tr>
 
					<% @cities.each do |city| %>
					<tr>
					<td align="center" >
						</br>
						<img src="http://localhost:3000/assets/<%=city.photo %>" class="img-rounded" alt="<%=city.photo %>" width="304" height="236"></br></br>
						<a href="<%=city_restaurants_path(city)%>" class="btn btn-default btn-md"><%=city.name%></a>&nbsp;&nbsp;&nbsp;
						<a href="<%=edit_city_path(city)%>" class="btn btn-info btn-md"><img src="http://localhost:3000/assets/edit.png" width="25" height="25" ></a>
					</td>
					</tr>
					<% end %>
					</table></p>
					<a href="<%=new_city_path%>" class="btn btn-default btn-xs">+ add new city</a>
                </div>
            </div>
        </div>
    </section>


  
    
	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-envelope"></span><br> mazi82x@gmail.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
        	<div class="container">
        		<p>Copyright xxx 2015</p>
        	</div>
        </div>
        
    </footer>
	
    <!-- jQuery -->
    <script src="http://localhost:3000/assets/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://localhost:3000/assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://localhost:3000/assets/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="http://localhost:3000/assets/custom.js"></script>

</body>

</html>

CityFoodReview/app/views/layouts_/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CityFoodReview</title>
<%= stylesheet_link_tag   "assets/stylesheets/custom"%>
  <%= csrf_meta_tags %>
</head>
<body>

</body>
</html>

CityFoodReview/app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Restaurants rewiev - Restaurants</title>
    <!-- Bootstrap Core CSS & Custom CSS-->
	<!--<%= stylesheet_link_tag   "http://localhost:3000/assets/custom.css" , media: 'all', 'data-turbolinks-track' => true%>-->


    <link href="http://localhost:3000/assets/bootstrap.min.css" rel="stylesheet">
	<link href="http://localhost:3000/assets/custom.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-togxglegle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                	<span class="glyphicon glyphicon-fire"></span> 
                	CITY FOOD REWIEV
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="http://localhost:3000">Home</a>
                    </li>
                    <li>
                        <a href="http://localhost:3000/cities">Restaurants</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ranks<span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="http://localhost:3000/cities">TOP 10</a></li>
							<li><a href="http://localhost:3000/cities">Budget rank</a></li>
						</ul>
					</li>
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>

	<!-- Header -->
    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1>Choose your restaurant</h1>
            </div>
        </div>
    </header>

	<!-- Content  -->
    <section class="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="http://localhost:3000/assets/pizza.jpg" alt="">
                </div>
                <div class="col-sm-6">
                	<h2 class="section-header">The list of restaurants in <strong><%=@city.name%></strong></h2>
                	<p class="lead text-muted"></p>
					<table width="100%" class="table table-hover">
					<% @city.restaurants.order("name").each do |restaurant| %>
					
					<tr bgcolor="#F5B145">

						<td colspan="3" align="center">
					<a  href="<%=city_restaurant_votes_path(@city	, restaurant)%>">
						<h2><%=restaurant.name%></h2>
					</a>
					</td>
					</tr>
					
					<tr>
						<td>Address: <strong><%= restaurant.address %></strong></br></br></td>
						<td>cuisine type: <strong><%= restaurant.cuisine %></strong></td>
						<td>
						<a href="<%=edit_city_restaurant_path(@city	, restaurant)%>" class="btn btn-default btn-md"><img src="http://localhost:3000/assets/edit.png" width="25" height="25" ></a>
						</td>
						
					</tr>
					
					<% end %>
					</table></p>
					</br>
                	<a href="<%=new_city_restaurant_path%>" class="btn btn-primary btn-xs">+add restaurant</a>&nbsp;&nbsp;&nbsp;
					<a href="<%=cities_path%>" class="btn btn-primary btn-xs"><--back to previous page</a>
                </div>                
                
            </div>
        </div>
    </section>

    
	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-envelope"></span><br> mazi82x@gmail.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
        	<div class="container">
        		<p>Copyright xxx 2015</p>
        	</div>
        </div>
        
    </footer>
	
    <!-- jQuery -->
    <script src="http://localhost:3000/assets/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://localhost:3000/assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://localhost:3000/assets/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="http://localhost:3000/assets/custom.js"></script>

</body>

</html>

CityFoodReview/app/views/votes/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Restaurants rewiev - Restaurant details</title>
    <!-- Bootstrap Core CSS & Custom CSS-->
	<!--<%= stylesheet_link_tag   "http://localhost:3000/assets/custom.css" , media: 'all', 'data-turbolinks-track' => true%>-->


    <link href="http://localhost:3000/assets/bootstrap.min.css" rel="stylesheet">
	<link href="http://localhost:3000/assets/custom.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts from Google -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    
</head>

<body>

    <!-- Navigation -->
    <nav id="siteNav" class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Logo and responsive toggle -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-togxglegle="collapse" data-target="#navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                	<span class="glyphicon glyphicon-fire"></span> 
                	CITY FOOD REWIEV
                </a>
            </div>
            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="navbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="active">
                        <a href="http://localhost:3000">Home</a>
                    </li>
                    <li>
                        <a href="http://localhost:3000/cities">Restaurants</a>
                    </li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ranks<span class="caret"></span></a>
						<ul class="dropdown-menu" aria-labelledby="about-us">
							<li><a href="http://localhost:3000/cities">TOP 10</a></li>
							<li><a href="http://localhost:3000/cities">Budget rank</a></li>
						</ul>
					</li>
                    <li>
                        <a href="#">About</a>
                    </li>
                </ul>
                
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>


	<!-- Content  -->
     <section class="content content-2">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                	<h1 class="section-header"><%=@restaurant.name%> in <%=@city.name%></h1></br>
					<p class="lead text-light">
						<img src="http://localhost:3000/assets/<%=@restaurant.photo%>" class="img-rounded" alt="<%=@restaurant.photo%>" width="304" height="236">
					</p>
                	<p class="lead text-light">Address: <strong><%=@restaurant.address%></strong></p>
					<p class="lead text-light">Served food: <strong><%=@restaurant.cuisine%></strong></p>
					<p class="lead text-light">Remark: <strong><%=@restaurant.remarks%></strong></p></br></br></br>
					<h4>Rates and comments:</h4>
					
					<% @restaurant.votes.each do |vote| %>
					<div id="comments">
						<p class="lead text-light"><%=vote.voter%></p>
						<p class="lead text-light">Rate: <%=vote.vote%></p>
						<p class="lead text-light">Comment: <%=vote.comment%></p>
				    </div></br>
					<% end %>
										
                	<a href="<%=new_city_restaurant_vote_path%>" class="btn btn-default btn-sx">+add your rate</a>&nbsp;&nbsp;&nbsp;
					<a href="<%=city_restaurants_path(@city)%>" class="btn btn-default btn-sx"><--back to previous page</a>
                </div>    
                <div class="col-sm-6">
                    <img class="img-responsive img-circle center-block" src="http://localhost:3000/assets/dish1.jpg" alt="">
                </div>            
				
                
            </div>
        </div>
    </section>    

    
	<!-- Footer -->
    <footer class="page-footer">
    
    	<!-- Contact Us -->
        <div class="contact">
        	<div class="container">
				<h2 class="section-heading">Contact Us</h2>
				<p><span class="glyphicon glyphicon-envelope"></span><br> mazi82x@gmail.com</p>
        	</div>
        </div>
        	
        <!-- Copyright etc -->
        <div class="small-print">
        	<div class="container">
        		<p>Copyright xxx 2015</p>
        	</div>
        </div>
        
    </footer>
	
    <!-- jQuery -->
    <script src="http://localhost:3000/assets/jquery-1.11.3.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://localhost:3000/assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="http://localhost:3000/assets/jquery.easing.min.js"></script>
    
    <!-- Custom Javascript -->
    <script src="http://localhost:3000/assets/custom.js"></script>

</body>

</html>